### ISSUE TITLE
Check Openshift observe command

### ISSUE THREAD

**Issue by sebgoa** [skippbox/kubewatch#39]
Openshift just release `observe`, merged with:
https://github.com/openshift/origin/pull/4196/files

We should look at it, it uses the prometheus golang library to watch resources...

**Comment by runseb** [comment]
see also thread:

https://github.com/kubernetes/kubernetes/issues/5164

**Comment by ngtuna** [comment]
So @sebgoa , basic feedback I have:

- `oc observe` basically relies on kubernetes `cache/reflector` in order to create a process of listing and watching changes in a given resource type (only one resource type could be watched. There is an open request for watching more than one in a single request: https://github.com/kubernetes/kubernetes/issues/1685).
- In `oc observe`, I am not really sure what prometheus is being used for (kind of collecting monitoring metrics), but definitely not for watching changes. Only reflector taking care of it.
- Reflector also being used in controller framework #25. Looking through the implementation, both observe and controller framework use reflector in the same way.
- Basic understanding of reflector:
  + create a FIFO queue to store resource items (for ex: services) and keep them in sync while the reflector process is running.
  + For each iteration, list all resource items and get the resource version at the moment of call, then use the resource version to watch its changes.
  + Watch changes of resource items via its version
  + the FIFO queue would be kept in sync with specific changes of resource items:
     - a new item is created -> add to queue
     - an item is updated -> update to queue
     - an item is deleted -> remove item from queue
- Then, `oc observe` popping items from queue and execute predefined corresponding actions.

Comment:

I am not sure if using cache/reflector is good or bad, it seems a little bit complicated. But it also seems to be a popular lib for watching k8s resource at this moment. So, we would try to adopt it.

**Comment by ngtuna** [comment]
close via #45
