### ISSUE TITLE
Consider to adopt a cli library for kubewatch

### ISSUE THREAD

**Issue by ngtuna** [skippbox/kubewatch#42]
I would prefer to use a cli lib for kubewatch in order to make its help looks more senses, compare to the current one:

```console
Usage of ./kubewatch:
  -alsologtostderr
    	log to standard error as well as files
  -config-file string
    	Configuration file
  -handler string
    	Handler for event, can be [slack, default], default handler is printing event (default "default")
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace (default :0)
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -reason string
    	Filter event by events, comma separated string
  -slack-channel string
    	Slack channel
  -slack-token string
    	Slack token
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
```

**Comment by sebgoa** [comment]
I don't have  good handle on the detailed flag, but yes, it should be built with cobra or something similar like kompose.

And based on what we want to listen to and publish to, we can configure the CLI.

Since this will run within a Kubernetes cluster, I created a basic deployment and made an early image. But that's the idea, CLI configuration and being run within a cluster as a Pod.

**Comment by ngtuna** [comment]
we should also consider to run kubewatch in `kube-system` namespace. That would make sense I think to make it run as a system-level service.

**Comment by sebgoa** [comment]
probably in its own namespace even.

**Comment by ngtuna** [comment]
Close via #44
